version: '3.9'

services:
  postgres:
    image: postgres
    container_name: workout-tracker-db
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - 5432:5432
    expose:
      - 5432
